apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot552
  labels:
    app: telegrambot552
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegrambot552
  template:
    metadata:
      labels:
        app: telegrambot552
    spec:
      containers:
        - name: telegrambot
          image: ivankalmykov/telegrambot:latest
          ports:
            - containerPort: 8080



